/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cnpj/{cnpj}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cnpj: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CnpjResponseDto"];
                        "application/json": components["schemas"]["CnpjResponseDto"];
                        "text/json": components["schemas"]["CnpjResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AtividadeDto: {
            code?: string;
            text?: string;
        };
        CnpjResponseDto: {
            cnpj?: string;
            status?: string;
            ultimaAtualizacao?: null | string;
            tipo?: string;
            porte?: string;
            nome?: string;
            fantasia?: string;
            abertura?: string;
            atividadePrincipal?: components["schemas"]["AtividadeDto"][];
            atividadesSecundarias?: components["schemas"]["AtividadeDto"][];
            naturezaJuridica?: string;
            logradouro?: string;
            numero?: string;
            complemento?: string;
            cep?: string;
            bairro?: string;
            municipio?: string;
            uf?: string;
            email?: string;
            telefone?: string;
            efr?: string;
            situacao?: string;
            dataSituacao?: string;
            motivoSituacao?: string;
            situacaoEspecial?: string;
            dataSituacaoEspecial?: string;
            capitalSocial?: string;
            qsa?: components["schemas"]["QsaDto"][];
            simples?: null | components["schemas"]["SimplesUnificadoDto"];
            simei?: null | components["schemas"]["SimplesUnificadoDto"];
        };
        HistoricoDto: {
            periodos_anteriores?: components["schemas"]["PeriodoAnteriorDto"][];
        };
        PeriodoAnteriorDto: {
            inicio?: string;
            fim?: string;
            detalhamento?: string;
        };
        QsaDto: {
            nome?: string;
            qual?: string;
            pais_origem?: string;
            nome_rep_legal?: string;
            qual_rep_legal?: string;
        };
        SimplesUnificadoDto: {
            optante?: boolean;
            dataOpcao?: null | string;
            dataExclusao?: null | string;
            ultimaAtualizacao?: null | string;
            historico?: null | components["schemas"]["HistoricoDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
